### ISSUE TITLE
Add a config for function style

### ISSUE THREAD

**Issue by yasinuslu** [czottmann/sublime-underscorejs-snippets#5]
Hi, can you add a config for using function-style instead of object-style. Many projects use and encourage us to use function-style. It will be better if we have option to choose.

**Comment by czottmann** [comment]
Not going to happen, sorry.

I'd recommend forking the project and "translating" all snippets to function style in the fork instead of adding them to this here project.  This way it'd be easier for interested parties to pick the style they prefer from Package Control.  (Also, personally, I'm not a fan of snippet packs that try to cover every conceivable use case.)

**Comment by yasinuslu** [comment]
Well said, i'll do that when i have time.
